### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by VegeBun-csj** [Zkvers/substrate-zk#1]
MileStone1:
- [x] Add groth16 proof system(In this chain, we use bellman lib), Adapt proof of bellman and snarkjs 
- [x] Add a practical example with zero knowledge proof(eg: rollup, game or the other application)
- [x] Add document about groth16(theory -> example tutorial)
- [ ] Add Docker file

MileStone2:
- [ ] Add plonk proof system
- [ ] Add a practical example with zero knowledge proof(eg: rollup, game or the other application)
- [ ] Add document about plonk(theory -> example tutorial)
- [ ] Add Docker file
